version: '3.8'

services:

  db:
    image: postgres:15.2
    container_name: best_viaje
    restart: always
    volumes:
      - ./db/sql/crear_esquema.sql:/docker-entrypoint-initdb.d/crear_esquema.sql
      - ./db/sql/datos.sql:/docker-entrypoint-initdb.d/datos.sql
    environment:
      - POSTGRES_DB=best_viaje
      - POSTGRES_USER=kevin
      - POSTGRES_PASSWORD=dunky
    ports:
      - "9797:5432" #5432 es el por defecto de postgress

#docker-compose down
#docker-compose up

#sudo docker exec -it best_viaje psql -U kevin -d best_viaje
#ALTER USER kevin WITH PASSWORD 'dunky';